//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.course_registerd = new HashSet<course_registerd>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int course_id { get; set; }
        public string course_pic { get; set; }
        public string course_title { get; set; }
        public string course_description { get; set; }
        public string course_goals { get; set; }
        public System.DateTime course_from_date { get; set; }
        public System.DateTime course_to_date { get; set; }
        public decimal course_price { get; set; }
        public int institute_id { get; set; }
    
        public virtual institute institute { get; set; }
        public virtual ICollection<course_registerd> course_registerd { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
