//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH
{
    using System;
    using System.Collections.Generic;
    
    public partial class institute
    {
        public institute()
        {
            this.courses = new HashSet<course>();
        }
    
        public int institute_id { get; set; }
        public string institute_name { get; set; }
        public string institute_city { get; set; }
        public string institute_address { get; set; }
        public string institute_phone_no { get; set; }
    
        public virtual ICollection<course> courses { get; set; }
    }
}
