//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.course_registerd = new HashSet<course_registerd>();
        }
    
        public int inv_id { get; set; }
        public int user_id { get; set; }
        public int course_id { get; set; }
        public decimal inv_total { get; set; }
        public System.DateTime inv_date { get; set; }
    
        public virtual course course { get; set; }
        public virtual ICollection<course_registerd> course_registerd { get; set; }
        public virtual user user { get; set; }
    }
}
